<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Resources_DownloadFAQ</name>
   <tag></tag>
   <elementGuidId>4591f8bd-90a2-4b0b-a865-bab13b835455</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@href=&quot;https://s3.amazonaws.com/assets.us.pirq/publications/Text-Club-FAQs.pdf&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
