<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>//a[@href=&quot;/digital-loyalty/main&quot;]</description>
   <name>nav_DigitalPunchCard_Portal_Homepage</name>
   <tag></tag>
   <elementGuidId>6dc20889-878a-4812-96b0-5a3224722886</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@href=&quot;/digital-loyalty/main&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
