<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_SignUpNow1_Por_TextClub</name>
   <tag></tag>
   <elementGuidId>4b8e1877-cabf-49b4-be15-192ae61b0664</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id=&quot;text_club_contact_button_one&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <value>//div[@id=&quot;text_club_contact_button_one&quot;]</value>
   </webElementXpaths>
</WebElementEntity>
