<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_FirstName_Por_TextClub_Step1</name>
   <tag></tag>
   <elementGuidId>c967312e-1890-4fb9-b44e-273978bee64c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id=&quot;business_first_name&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <value>//input[@id=&quot;business_first_name&quot;]</value>
   </webElementXpaths>
</WebElementEntity>
