<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_CreditCardNumber_Por_TextClub_Step2</name>
   <tag></tag>
   <elementGuidId>fc0afcf5-c1bf-451f-bab5-11a07ed6bf6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id=&quot;credit_card_number_field&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <value>//input[@id=&quot;credit_card_number_field&quot;]</value>
   </webElementXpaths>
</WebElementEntity>
