<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lnk_VipOverview_System_Dashboard</name>
   <tag></tag>
   <elementGuidId>9b7c36c2-dc98-4eb3-9a96-9083cc46142f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;sidebar&quot;]/ul/li[12]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <value>//*[@id=&quot;sidebar&quot;]/ul/li[12]/a</value>
   </webElementXpaths>
</WebElementEntity>
