<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lnk_ReMarketingCampaigns_System_Dashboard</name>
   <tag></tag>
   <elementGuidId>42ec34bc-e04e-4bb5-9230-5a5eff23b8cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(@href,'re-marketing/campaign-history')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <value>//a[contains(@href,'re-marketing/campaign-history')]</value>
   </webElementXpaths>
</WebElementEntity>
