<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Accept_System_TermsAgreement</name>
   <tag></tag>
   <elementGuidId>c71a5965-afef-4e13-aa02-1bd5687a5048</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name=&quot;submit_merchant_service_agreement_form&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <value>//input[@name=&quot;submit_merchant_service_agreement_form&quot;]</value>
   </webElementXpaths>
</WebElementEntity>
