<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lnk_Support_System_Merchant</name>
   <tag></tag>
   <elementGuidId>e768871f-d043-46e7-b6f7-75af752d6bd9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@href=&quot;/merchant/support&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <value>//a[@href=&quot;/merchant/support&quot;]</value>
   </webElementXpaths>
</WebElementEntity>
