<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lbl_Congratulations_Por_Dig_Step3</name>
   <tag></tag>
   <elementGuidId>c82ad918-b9f9-420d-8751-a8d84a551561</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h1[text()='Congratulations!']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <value>//h1[text()='Congratulations!']</value>
   </webElementXpaths>
</WebElementEntity>
