<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lnk_PirqServiceAgreement_Por_Dig_Step2</name>
   <tag></tag>
   <elementGuidId>a80dabbb-83c9-48cd-965f-533c61f208a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@href=&quot;/pirq/msa&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <value>//a[@href=&quot;/pirq/msa&quot;]</value>
   </webElementXpaths>
</WebElementEntity>
