<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_CVV_Por_Dig_Step2</name>
   <tag></tag>
   <elementGuidId>3c485bbb-399d-4931-9397-ce2f0090a5d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@data-encrypted-name=&quot;cvv&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <value>//input[@data-encrypted-name=&quot;cvv&quot;]</value>
   </webElementXpaths>
</WebElementEntity>
