<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chx_SameAsBusiness_Por_Dig_Step2</name>
   <tag></tag>
   <elementGuidId>448dd8e8-229f-41dd-9371-86cdc583b605</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id=&quot;same_as_business_selected&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <value>//input[@id=&quot;same_as_business_selected&quot;]</value>
   </webElementXpaths>
</WebElementEntity>
