<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>drp_Date_Por_Dig_Step2</name>
   <tag></tag>
   <elementGuidId>326f72ba-6f21-4258-bded-a029422f2e65</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@data-encrypted-name=&quot;month&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <value>//select[@data-encrypted-name=&quot;month&quot;]</value>
   </webElementXpaths>
</WebElementEntity>
