<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>drp_State_Por_Dig_Step2</name>
   <tag></tag>
   <elementGuidId>dfa23b5a-a090-461d-87d5-818e9235fc4e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id=&quot;credit_card_state&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <value>//select[@id=&quot;credit_card_state&quot;]</value>
   </webElementXpaths>
</WebElementEntity>
