<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>drp_State_Por_Dig_Step1</name>
   <tag></tag>
   <elementGuidId>d9a0dd01-7730-40b1-90b4-9c902607b968</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id=&quot;business_state&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <value>//select[@id=&quot;business_state&quot;]</value>
   </webElementXpaths>
</WebElementEntity>
