<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lnk_SignUpNow_Portal_Digital</name>
   <tag></tag>
   <elementGuidId>cd6647d2-ce29-4207-bc97-685edf54c3b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//a[@href=&quot;/digital-loyalty/signup&quot;])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <value>(//a[@href=&quot;/digital-loyalty/signup&quot;])[1]</value>
   </webElementXpaths>
</WebElementEntity>
