<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>rad_Plan60_Por_Dig_Step2</name>
   <tag></tag>
   <elementGuidId>a198a8d5-5242-4026-9e7f-9dc7968a460d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id=&quot;plan_obid_x2CWDll2t0LUg&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <value>//input[@id=&quot;plan_obid_x2CWDll2t0LUg&quot;]</value>
   </webElementXpaths>
</WebElementEntity>
