<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>rad_Plan30_Por_Dig_Step2</name>
   <tag></tag>
   <elementGuidId>b9414b41-f001-4714-9257-467963fcb325</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id=&quot;plan_obid_x0lkTWq44aDI5&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <value>//input[@id=&quot;plan_obid_x0lkTWq44aDI5&quot;]</value>
   </webElementXpaths>
</WebElementEntity>
