<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_CreditCardNumber_Por_Dig_Step2</name>
   <tag></tag>
   <elementGuidId>b2a84ade-6b87-4ec0-a870-06e7fff001ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id=&quot;credit_card_number_field&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <value>//input[@id=&quot;credit_card_number_field&quot;]</value>
   </webElementXpaths>
</WebElementEntity>
