<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_Description_Por_Dig_Step3</name>
   <tag></tag>
   <elementGuidId>11a5e664-f355-4465-82ab-12a53da5df2a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id=&quot;reward_description&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <value>//textarea[@id=&quot;reward_description&quot;]</value>
   </webElementXpaths>
</WebElementEntity>
