<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_Rules_Por_Dig_Step3</name>
   <tag></tag>
   <elementGuidId>0dadac3c-2a3b-463b-bd7e-fe82e7bef92c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id=&quot;reward_rules&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <value>//textarea[@id=&quot;reward_rules&quot;]</value>
   </webElementXpaths>
</WebElementEntity>
