<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_LastName_Por_Dig_Step2</name>
   <tag></tag>
   <elementGuidId>8d4251e5-5c36-41bf-8671-43a0a05e7c2d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id=&quot;credit_card_last_name&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <value>//input[@id=&quot;credit_card_last_name&quot;]</value>
   </webElementXpaths>
</WebElementEntity>
