<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lnk_activate_Inbox</name>
   <tag></tag>
   <elementGuidId>aa33eb0f-d5d3-4b84-97e5-da73a1cacb83</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(@href,'http://merchant.staging-1.pirq.com/confirm_account/')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <value>//a[contains(@href,'http://merchant.staging-1.pirq.com/confirm_account/')]</value>
   </webElementXpaths>
</WebElementEntity>
