<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_SignUpNow3_Por_TextClub</name>
   <tag></tag>
   <elementGuidId>b6cbd182-b309-4cd6-bd3c-8d4be13fb371</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id=&quot;text_club_contact_button_three&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <value>//div[@id=&quot;text_club_contact_button_three&quot;]</value>
   </webElementXpaths>
</WebElementEntity>
