<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chx_SameAsBusiness_Por_TextClub_Step2</name>
   <tag></tag>
   <elementGuidId>41984509-5495-4c07-b0a0-f115322b4730</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id=&quot;same_as_business_selected&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <value>//input[@id=&quot;same_as_business_selected&quot;]</value>
   </webElementXpaths>
</WebElementEntity>
