<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lbl_Congratulations_Por_TextClub_Step3</name>
   <tag></tag>
   <elementGuidId>a5b2d695-9c88-495c-9407-71f52cd4d9aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[text()[contains(.,'Congratulations!')]]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <value>//*[text()[contains(.,'Congratulations!')]]</value>
   </webElementXpaths>
</WebElementEntity>
