<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lnk_ClickHereToSeeAllPlans_Por_TextClub</name>
   <tag></tag>
   <elementGuidId>00f928ac-bd22-4761-be63-931e869b3227</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id=&quot;pricing_plans_link&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <value>//span[@id=&quot;pricing_plans_link&quot;]</value>
   </webElementXpaths>
</WebElementEntity>
