<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_Rules_Por_Dig_Step3</name>
   <tag></tag>
   <elementGuidId>18d659bb-4005-4258-b313-8f8786e37f46</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id=&quot;reward_rules&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <value>//textarea[@id=&quot;reward_rules&quot;]</value>
   </webElementXpaths>
</WebElementEntity>
