<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_CVV_Por_TextClub_Step2</name>
   <tag></tag>
   <elementGuidId>f996a8c8-a8f1-47f5-aa6b-c92b56f45d6c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@data-encrypted-name=&quot;cvv&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <value>//input[@data-encrypted-name=&quot;cvv&quot;]</value>
   </webElementXpaths>
</WebElementEntity>
