<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lnk_Dashboard_System_Dashboard</name>
   <tag></tag>
   <elementGuidId>21691eef-75ba-433b-936e-db072c128657</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id=&quot;sidebar&quot;]//li[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <value>//div[@id=&quot;sidebar&quot;]//li[2]</value>
   </webElementXpaths>
</WebElementEntity>
