<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lnk_LoyaltyDashboard_System_Dashboard</name>
   <tag></tag>
   <elementGuidId>c76b7aa1-8448-477e-a8f1-598eb94e09a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(@href,'loyalty')]/div/div[contains(text(),'Loyalty')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <value>//a[contains(@href,'loyalty')]/div/div[contains(text(),'Loyalty')]</value>
   </webElementXpaths>
</WebElementEntity>
